version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-volanty
    volumes:
      - $HOME/data/mongo-data:/data/db
      - $HOME/data/mongo-bkp:/data/bkp
    restart: always
    ports:
      - 27017:27017

  app:
    image: volanty-api
    build: .
    restart: always
    container_name: cav-api
    ports:
      - 8081:8081
    working_dir: /application
    depends_on:
      - mongodb
    links:
      - mongodb
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb/cav




